operations:
  view:
    - type: web
      impl: index.html
actions: actions
web: web-src
runtimeManifest:
  packages:
    dx-excshell-1:
      license: Apache-2.0
      actions:
        webhook:
          function: actions/webhook/index.js
          web: raw
          runtime: 'nodejs:16'
          inputs:
            LOG_LEVEL: debug
            SOCKET_CLUSTER_ID: $SOCKET_CLUSTER_ID
            SOCKET_API_KEY: $SOCKET_API_KEY
            SOCKET_API_SECRET: $SOCKET_API_SECRET
          annotations:
            require-adobe-auth: false
            final: true
        get-auth:
          function: actions/get-auth/index.js
          web: 'yes'
          runtime: 'nodejs:16'
          inputs:
            LOG_LEVEL: debug
            IMS: $IMS
          annotations:
            require-adobe-auth: false
            final: true
